feat(eighth): add ability to set 'signup_time' on eighth block creation
tjcsl/ion pull request #1133
Opened 2021-05-07 19:55 UTC by nkenschaft

closes #1097

2021-05-12 21:16 UTC, Laur04 requested changes
In addition to fixing the broken tests, please change the commit message, replacing "added" with "add". Commit messages in general, but definitely for Ion, should be in the format of an imperative. For example, "fixed issue X", not "fixing issue X", "fixed issue X" or "will fix issue X"

2021-05-14 19:30 UTC, nkenschaft commented
> In addition to fixing the broken tests, please change the commit message, replacing "added" with "add". Commit messages in general, but definitely for Ion, should be in the format of an imperative. For example, "fixed issue X", not "fixing issue X", "fixed issue X" or "will fix issue X"

Done.

2021-05-14 22:39 UTC, Laur04 requested changes

2021-05-14 22:39 UTC, Laur04 commented on intranet/apps/eighth/views/admin/blocks.py
> +        signup_time = request.GET.get("signup_time")
```suggestion
```
You don't need this, as `signup_time` only matters on the POST request.

2021-05-14 22:39 UTC, Laur04 commented on intranet/apps/eighth/views/admin/blocks.py
> +        signup_time = request.POST.get("signup_time")
```suggestion
    signup_time = request.POST.get("signup_time") if "signup_time" in request.POST else datetime.time(12, 40)
```

2021-05-14 22:39 UTC, Laur04 commented on intranet/apps/eighth/views/admin/blocks.py
> +    signup_time = datetime.time(12, 40)
```suggestion
```

2021-05-14 22:39 UTC, Laur04 commented on intranet/apps/eighth/views/admin/blocks.py
> +                    messages.success(request, "Successfully added {} Block on {} at {}".format(ltr, fmtdate, signup_time))
```suggestion
                    messages.success(request, "Successfully added {} Block on {} with signups shown to students as closing at {}".format(ltr, fmtdate, signup_time))
```

2021-05-14 22:39 UTC, Laur04 commented on intranet/templates/eighth/admin/add_block.html
> +            <th><label>Set time:</label></th>
```suggestion
            <th><label>Set signup locking time:</label></th>
```

2021-05-14 22:39 UTC, Laur04 commented on intranet/templates/eighth/admin/add_block.html
> +                <input type="time" name="signup_time" size="12" maxlength="10">
```suggestion
                <input type="time" name="signup_time" size="12" maxlength="10" value="12:40">
```

2021-05-14 22:39 UTC, Laur04 commented on intranet/templates/eighth/admin/add_block.html
> +    console.debug(time, "time");
```suggestion
```

2021-05-19 19:18 UTC, closed without merging