docs(testing): update testing docs
tjcsl/ion pull request #1162
Opened 2021-07-06 01:00 UTC by Laur04

## Brief description of rationale

2021-07-22 19:43 UTC, smayya337 requested changes
These are all very small changes, because the rest of it is pretty good!

2021-07-22 19:43 UTC, smayya337 commented on docs/developing/testing.rst
> +To actually execute tests, run ``pytest`` inside your vagrant environmnet. If you want to only test a specific apps, you can run ``pytest <apps_name>``. Do note that this deletes and re-creates the d
```suggestion
To actually execute tests, run ``pytest`` inside your vagrant environment. If you want to only test a specific app, you can run ``pytest <apps_name>``. Do note that this deletes and re-creates the db from scratch each time, so you may want to pass the ``-k`` option when developing tests as it significantly reduces run-time.
```

2021-07-22 19:43 UTC, smayya337 commented on docs/developing/testing.rst
> +Generally, there are two ways that you test Ion's code. These all not comprehensive, but should work for most cases. The first is calling methods directly; the second is making a GET or POST request
```suggestion
Generally, there are two ways that you test Ion's code. These are not comprehensive, but should work for most cases. The first is calling methods directly; the second is making a GET or POST request to the view that you are interested in testing. The best tests utilize both. After you do either/both of these to call the code, you should use assertions to see if the code behaved as expected. A list of assertion options can be found `here <https://docs.python.org/3/library/unittest`_.html#assert-methods>`. A useful tool for making requests to the view is ``self.client``. More documentation on that can be found `here <https://docs.djangoproject.com/en/3.2/topics/testing/tools/>`_. Alternatively, just search through Ion's testing files for examples of using `self.client`.
```

2021-07-22 19:43 UTC, smayya337 commented on docs/developing/testing.rst
> +Ion has lots of tests; the following are examples of very well written ones. Note the abundance of comments and the attention to detail. Test everything.
```suggestion
Ion has lots of tests; the following are examples of very well-written ones. Note the abundance of comments and the attention to detail. Test everything.

- `Polls <https://github.com/tjcsl/ion/blob/dev/intranet/apps/polls/tests.py>`_ - Note the thoroughness of the checks; assertions are made even when nothing should have changed.
- `Emailfwd <https://github.com/tjcsl/ion/blob/dev/intranet/apps/emailfwd/tests.py>`_ - Note the use of `self.client` and checking `messages` generated by the page.
- `Eighth <https://github.com/tjcsl/ion/tree/dev/intranet/apps/eighth/tests>`_ - If a testing method has been used in Ion, it's in ``eighth``. This is the most complicated and also the most thorough set of tests that Ion has.
```
`If a testing method has been used in Ion` might need a little bit of rewording - it comes across as a touch confusing.

2021-07-30 14:12 UTC, smayya337 approved these changes
LGTM!

2021-07-30 14:13 UTC, etnguyen03 approved these changes
LGTM too

2021-07-30 14:21 UTC, merged