feat(polls): add error message to modifying polls after end date
tjcsl/ion pull request #1166
Opened 2021-07-31 15:08 UTC by pizzalemon

Closes #1128

## Proposed changes
- 
- 
- 

## Brief description of rationale

2021-07-31 15:19 UTC, Laur04 requested changes
What you have looks good, but as stated in the issue, the user should be redirected back to the page they came from. If they came from the page with ?show_all=True set, they should be redirected back to it.

2021-07-31 15:21 UTC, smayya337 commented
Also, don't worry about the CI failures - they appear to be unrelated to your work. We'll take a look at them later.

2021-07-31 18:30 UTC, pizzalemon commented
I added another commit which should do that. I made it so it should go back to polls/ in case it's from there (and of course polls?show_all=1), but as far as I can tell, you can't access an old poll unless you have show all on, so the request would always be from polls?show_all=1 anyways, but the way you phrased it in the issue made it sound like I should plan for it being from polls/, so I made it like that in the commit.

2021-08-01 16:18 UTC, Laur04 requested changes
squash your commits into one commit with the commit message of the first.

2021-08-01 16:21 UTC, Laur04 commented
You also need to fix the CI for formatting and linting. Don't worry about tests.

2021-08-01 19:02 UTC, pizzalemon commented
It should be good I think?

2021-08-01 20:51 UTC, Laur04 requested changes
Otherwise, LGTM. The tests will pass tomorrow.

2021-08-01 20:51 UTC, Laur04 commented on intranet/apps/polls/views.py
> +            return redirect(reverse("polls") + "?show_all=1")
```suggestion
            return redirect(reverse("polls", kwargs={"show_all":1}))
```

2021-08-01 23:03 UTC, Laur04 requested changes
Okay, I promise that this is the last thing, but put it back to how it was before I suggested a change please. Sorry, that's a syntax for a different version that actually breaks here. Didn't think about that until I actually tested it and it broke unfortunately. After that, I'll run the CI tomorrow and then merge.

2021-08-02 14:47 UTC, Laur04 approved these changes
LGTM, pending CI. Congrats on your first contribution.

2021-08-02 14:53 UTC, merged