feat(users): support non-binary genders
tjcsl/ion pull request #1236
Opened 2022-01-28 20:00 UTC by shahsalonik

## Proposed changes
- Change User.gender to a string
- Add an "is_nonbinary" method

## Brief description of rationale
TJ has a large non-binary population; this change could help with inclusivity.

2022-02-18 20:18 UTC, shahsalonik commented
I think I'm done with this.

2022-02-23 19:28 UTC, Laur04 requested changes
This is good in terms of model changes, but there are many other places throughout Ion's codebase where gender is references in templates, views and management commands. I'd Ctrl+F through the entire codebase to find references to gender and make sure they fit with this new variable type. Installing Visual Studio would probably be helpful.

2022-05-02 19:13 UTC, Laur04 commented
What's the status here?

2022-05-20 13:55 UTC, Laur04 requested changes
Let's talk about how best to migrate this change.

2022-08-09 19:40 UTC, Rushilwiz commented on intranet/apps/users/models.py
> +        return self.gender
```python
return self.gender or ""
```
In case gender is `None`. I think the serializer is the only thing that uses this field.

2022-08-12 18:13 UTC, merged