feat: add csl statusy integration in emergency. refs #1211
tjcsl/ion pull request #1304
Opened 2022-05-20 18:47 UTC by dianalin2

2022-05-22 18:33 UTC, smayya337 requested changes
I noticed one issue that prevented the CSL status updates from showing up on my end, as well as a few places to tweak how everything is displayed. Besides that, the only other thing I can think of is maybe removing the "-FCPS" in the bottom right corner of the announcement area, and this should be good (though I defer to @Laur04 there).

2022-05-22 18:33 UTC, smayya337 commented on intranet/apps/emerg/views.py
> +    for system in csl_status['systems']:
I think that with the code that's currently here, the status isn't updated if there's a  CSL issue, so you'll never see a CSL issue unless there's an FCPS emergency announcement as well. Having `status` update whenever there's a CSL issue will fix that. Also, we probably don't want informational updates to be in the yellow (e.g. current Borg cluster maintenance, so we can filter that out), and we shouldn't have multiple instances of the same thing in the `announcements` list (the JSON has the same issue under each affected system).

With all that said, here's how I worked around all of this:
```py
status = False
    for system in csl_status['systems']:
        if system['status'] != 'ok':
            status = True
            issues = system['unresolvedIssues']
            for issue in issues:
                desc = requests.get(issue['permalink']).text
                soup = BeautifulSoup(desc, "html.parser")
                desc = soup.find_all('p')[1].text
                val = {"title": issue['title'], "body": desc}
                if val not in announcements and issue['severity'] != 'notice':
                    announcements.append(val)
```

2022-05-24 15:14 UTC, Laur04 requested changes
Changes look fine to me.

@smayya337 what prevents this from pulling even the "All Good" status from the status page?

@dianalin2 fix CI, then you're good.

2022-05-24 17:00 UTC, Laur04 commented
@dianalin2 you've got merge conflicts now. `dev` was updated recently, so rebase against it.

2022-05-24 17:35 UTC, Laur04 commented
@dianalin2 don't worry about Codacy

2022-05-24 17:36 UTC, Laur04 requested changes
LGTM - squash commits and I'll merge

2022-05-24 18:53 UTC, merged

2022-05-24 18:55 UTC, Laur04 commented
@dianalin2 I didn't see it this time, so my bad, but in the future, please remove the old commit messages from the squashed commit message.