Migrate from setup.py to pyproject.toml
tjcsl/ion pull request #1611
Opened 2023-11-29 04:27 UTC by pefoley2

Based on https://setuptools.pypa.io/en/latest/userguide

## Proposed changes

Migrate configuration from setup.py to pyproject.toml, but leave a stub setup.py to avoid breaking setup.py test and friends.

## Brief description of rationale

Setuptools is discouraging direct usage of setup.py https://setuptools.pypa.io/en/latest/userguide/quickstart.html#transitioning-from-setup-py-to-setup-cfg

2023-12-09 15:48 UTC, alanzhu0 requested changes
Hey there! Thanks so much for your contribution. 

Your setup.py -> pyproject.toml changes look great. The only thing is there are a few files not directly connected to that change in the commit - I will point those out in the file comments. Could you remove those files from the commit?

Thanks!

2023-12-09 15:48 UTC, alanzhu0 commented on Ion.egg-info/SOURCES.txt
Please leave secret.py in SOURCES.txt

2023-12-09 15:48 UTC, alanzhu0 commented on Ion.egg-info/top_level.txt
I don't think this should be removed?

2023-12-09 15:48 UTC, alanzhu0 commented on intranet/apps/notifications/emails.py
Please exclude this file from the commit.

2023-12-09 15:48 UTC, alanzhu0 commented on requirements.txt
What was the change here? Is it just Git being weird?

2024-05-21 21:58 UTC, NotFish232 commented
Closed in favor of #1648

2024-05-21 21:58 UTC, closed without merging