Add `.pre-commit`
tjcsl/ion pull request #1659
Opened 2024-04-07 01:44 UTC by JasonGrace2282

## Proposed changes
- Use `pre-commit` for linting
- Maintainers will add `pre-commit ci` so that if pre-commit fails, fixes will be pushed without having to run scripts.

## Brief description of rationale
Running scripts is annoying

### Note
This is not yet done (and damn do we have a lot of misspellings xD)

2024-04-07 21:37 UTC, JasonGrace2282 commented
To reiterate what I said on matterless:
The current problem is (to the best of my knowledge) that `black` and `autopep8` interfere with each other. Black will format some files, then autopep8 will go in and fix those. This was fine in scripts where it simply merged both outputs (with autopep8 taking priority), but with `pre-commit` it counts a check as a fail if it modifies files. As such, both black and autopep8 will fail each run.
The possible solutions to this I can think of include:
* Remove `autopep8` and stick with `black`
* Remove `black` and only use `autopep8`
* Don't use either, and use something like `ruff`
  * I'm a little bit biased, but this is my preferred option
* Do something like:
```yaml
- repo: local
  hooks:
    id: format
    entry: ./scripts/format.sh && test -z "$(git status --porcelain=v1)"
```
which I'm not sure would work with `pre-commit ci`

2024-05-04 14:11 UTC, JasonGrace2282 commented
I think this PR is _mostly_ ready to be reviewed, just need to find out what's causing the chaos with sorting imports.
Some benchmarks on my system:
* `time pre-commit run --all-files` takes 11.32 seconds (user)
* `time ruff check intranet/**/*.py` takes 0.45 seconds (user)
* `time ruff lint intranet/**/*.py` takes 0.04 seconds (user)

2024-05-04 15:33 UTC, JasonGrace2282 commented
In order to get the tests to pass (specifically flake8) in #1673, I had to make some changes that don't agree with the ruff (or black for that matter!) in this PR. As such, the changes in that PR aren't 100% reflective of the changes needed here (but it's a pretty small and easy to review diff).

2024-07-05 20:29 UTC, NotFish232 requested changes

2024-07-05 20:29 UTC, NotFish232 commented on intranet/apps/eighth/tests/admin/test_admin_groups.py
This diff doesnt look right, make sure to look through all the changes before review :)
Some of the other changes seem to have the same issues as the last massive diff, i.e. the bad_strings from fcps

2024-07-06 01:32 UTC, JasonGrace2282 commented on intranet/apps/eighth/tests/admin/test_admin_groups.py
Oops, forgot to check that! Should be fixed now (permanently, hopefully), thanks for taking the time to review :)

2024-08-11 21:15 UTC, merged